name: Continuous Integration 
on:
  pull_request:
  push:
    tags:
      - 'v*'

jobs:
  format_code:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo code
        uses: actions/checkout@v4
      - name: Setup go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23.1
      - name: Run linting
        run: | 
          go fmt ./...
          go vet ./...

  build_binaries:
    runs-on: ubuntu-latest
    needs: format-code
    strategy:
      matrix:
        os: [linux, macos, windows]
        go-version: [1.23.1]

    steps:
      - name: Check out repo code
        uses: actions/checkout@v4

      - name: Setup go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}

      - name: Build binaries for {{ matrix.os }}
        run: | 
          GOOS=${{ matrix.os }} GOARCH=amd64 go build -ldflags='-s -w' -o pyvm-${{ matrix.oss}}-amd64

      - name: Upload release binary
        uses: softprops/actio-gh-release@v1
        with:
          files: |
            pyvm-${{ matrix.os }}-amd64

          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
  release:
    needs: build_binaries
    runs-on: ubuntu-latest
    steps:
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            pyvm-linux-amd64
            pyvm-macos-amd64
            pyvm-windows-amd64

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
