name: Continuous Integration 
on:
  pull_request:
  push:

jobs:
  format_code:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo code
        uses: actions/checkout@v4
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: 1.23.1
      - name: Run linting
        run: | 
          go fmt ./...
          go vet ./..
